package hnsw

import (
	"errors"
	"runtime"
	"sync"

	"dmarro89.github.com/hnsw-go/structs"
)

type BulkBuildConfig struct { Workers int; BatchSize int; EfConstruction int }
func DefaultBulkBuildConfig() BulkBuildConfig { workers:=runtime.GOMAXPROCS(0);if workers<1{workers=1};return BulkBuildConfig{Workers:workers,BatchSize:max(32,workers*16)} }
type insertionProposal struct{id int;level int;neighbors [][]int}
type proposalJob struct{idx int;snapshotNodes []*structs.Node;snapshotEntry *structs.Node;vector []float32;id,level int}
type proposalResult struct{idx int;proposal insertionProposal}
type proposalWorkerPool struct{jobs chan proposalJob;results chan proposalResult;wg sync.WaitGroup}
func newProposalWorkerPool(h *HNSW,workers,batchSize,efConstruction,initialVisited int)*proposalWorkerPool{p:=&proposalWorkerPool{jobs:make(chan proposalJob,batchSize),results:make(chan proposalResult,batchSize)};for range workers{p.wg.Add(1);go func(){defer p.wg.Done();ctx:=newSearchContext(max(initialVisited,efConstruction));rb:=make([]int,0,efConstruction);eb:=make([]int,0,efConstruction);for j:=range p.jobs{pr,nr,ne:=h.computeInsertionProposal(j.snapshotNodes,j.snapshotEntry,j.vector,j.id,j.level,efConstruction,ctx,rb,eb);rb,eb=nr,ne;p.results<-proposalResult{j.idx,pr}}}()};return p}
func(p *proposalWorkerPool)compute(nodes []*structs.Node,entry *structs.Node,vectors [][]float32,levels []int,startID int)[]insertionProposal{out:=make([]insertionProposal,len(vectors));for i:=range vectors{p.jobs<-proposalJob{i,nodes,entry,vectors[i],startID+i,levels[i]}};for range vectors{r:=<-p.results;out[r.idx]=r.proposal};return out}
func(p *proposalWorkerPool)close(){close(p.jobs);p.wg.Wait()}

func(h *HNSW)BuildParallel(vectors [][]float32,cfg BulkBuildConfig)error{
	if len(vectors)==0{return nil};if cfg.Workers<=0{cfg.Workers=runtime.GOMAXPROCS(0);if cfg.Workers<1{cfg.Workers=1}};if cfg.BatchSize<=0{cfg.BatchSize=max(32,cfg.Workers*16)};if cfg.EfConstruction<=0{cfg.EfConstruction=h.EfConstruction};if cfg.EfConstruction<=0{return errors.New("EfConstruction must be positive")};for i,v:=range vectors{if len(v)==0{return errors.New("vector cannot be empty at batch index "+itoa(i))}}
	h.mutex.Lock();defer h.mutex.Unlock();if cfg.BatchSize==1{old:=h.EfConstruction;h.EfConstruction=cfg.EfConstruction;defer func(){h.EfConstruction=old}();id:=len(h.Nodes);h.ensureNodeCapacity(id+len(vectors));h.ensureVisitedCapacity(id+len(vectors)-1);buf:=make([]int,0,h.EfConstruction);for _,v:=range vectors{buf=h.insertLocked(v,id,buf);id++};return nil}
	nextID:=len(h.Nodes);h.ensureNodeCapacity(nextID+len(vectors));h.ensureVisitedCapacity(nextID+len(vectors)-1);levels:=make([]int,len(vectors));for i:=range vectors{levels[i]=h.RandomLevel()};start:=0;previousScratch:=make([]int,0,max(h.Mmax,h.Mmax0)+1);if h.EntryPoint==nil{first:=insertionProposal{id:nextID,level:levels[0],neighbors:make([][]int,levels[0]+1)};previousScratch=h.applyInsertionProposalScratch(vectors[0],first,previousScratch);nextID++;start=1};if start>=len(vectors){return nil};wc:=min(cfg.Workers,min(cfg.BatchSize,len(vectors)-start));workers:=newProposalWorkerPool(h,wc,cfg.BatchSize,cfg.EfConstruction,max(len(h.Nodes),cfg.EfConstruction));defer workers.close();for bs:=start;bs<len(vectors);bs+=cfg.BatchSize{be:=min(bs+cfg.BatchSize,len(vectors));bv:=vectors[bs:be];proposals:=workers.compute(h.Nodes,h.EntryPoint,bv,levels[bs:be],nextID);for i,p:=range proposals{previousScratch=h.applyInsertionProposalScratch(bv[i],p,previousScratch)};nextID+=len(bv)};return nil
}
func(h *HNSW)computeInsertionProposal(nodes []*structs.Node,entry *structs.Node,vector []float32,id,level,ef int,ctx *searchContext,rb,eb []int)(insertionProposal,[]int,[]int){p:=insertionProposal{id:id,level:level,neighbors:make([][]int,level+1)};if entry==nil{return p,rb[:0],eb[:0]};ep:=entry;eb=append(eb[:0],ep.ID);top:=ep.Level;for lc:=top;lc>level;lc--{ne:=greedySearchLayerNodes(vector,ep,lc,nodes,h.DistanceFunc);if ne==nil{break};ep=ne;eb=append(eb[:0],ep.ID)};for lc:=min(top,level);lc>=0;lc--{nearest:=searchLayerWithEntriesBufferContext(ctx,nodes,h.DistanceFunc,vector,eb,ef,lc,rb);n:=min(len(nearest),h.M);if n>0{p.neighbors[lc]=append(p.neighbors[lc][:0],nearest[:n]...);eb=append(eb[:0],nearest...);rb=nearest[:0]}else{p.neighbors[lc]=p.neighbors[lc][:0];eb=eb[:0];rb=rb[:0]}};return p,rb,eb}
func(h *HNSW)applyInsertionProposal(vector []float32,p insertionProposal){n:=h.appendNode(p.id,vector,p.level);if h.EntryPoint==nil{h.EntryPoint=n;return};for l:=min(p.level,len(p.neighbors)-1);l>=0;l--{m:=h.Mmax;if l==0{m=h.Mmax0};h.updateBidirectionalConnectionsBuilder(n,p.neighbors[l],l,m)};if p.level>h.EntryPoint.Level{h.EntryPoint=n}}
func(h *HNSW)updateBidirectionalConnectionsBuilder(q *structs.Node,neighbors []int,level,maxConn int){q.Neighbors[level]=q.Neighbors[level][:0];for _,id:=range neighbors{neighbor:=h.Nodes[id];if level>=len(neighbor.Neighbors){continue};accepted:=false;if len(neighbor.Neighbors[level])+1<=maxConn{l:=len(neighbor.Neighbors[level]);if l<cap(neighbor.Neighbors[level]){neighbor.Neighbors[level]=append(neighbor.Neighbors[level],q.ID)}else{nn:=make([]int,l+1,l+2);copy(nn,neighbor.Neighbors[level]);nn[l]=q.ID;neighbor.Neighbors[level]=nn};accepted=true}else{previous:=append([]int(nil),neighbor.Neighbors[level]...);c:=h.selectClosestNeighborIDs(neighbor,neighbor.Neighbors[level],q.ID,maxConn);neighbor.Neighbors[level]=neighbor.Neighbors[level][:len(c)];copy(neighbor.Neighbors[level],c);accepted=containsNeighborID(neighbor.Neighbors[level],q.ID);for _,d:=range previous{if containsNeighborID(neighbor.Neighbors[level],d){continue};dn:=h.Nodes[d];if level>=len(dn.Neighbors){continue};dn.Neighbors[level]=removeNeighborID(dn.Neighbors[level],neighbor.ID)}};if accepted{q.Neighbors[level]=append(q.Neighbors[level],id)}}}
func itoa(n int)string{if n==0{return"0"};var b[20]byte;i:=len(b);for n>0{i--;b[i]=byte('0'+n%10);n/=10};return string(b[i:])}
